name: Update IPTV Link
on:
  schedule:
    - cron: '0 */6 * * *' # يعمل تلقائياً كل 6 ساعات
  workflow_dispatch: # يتيح لك التشغيل اليدوي

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # إذن الكتابة ضروري لحفظ الملف ودعمه في المستودع
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install selenium webdriver-manager PySocks # 👈 أضفنا PySocks هنا ليفهم البروكسي من نوع Socks5

      - name: Run script
        run: python script.py

      - name: Commit and Push Changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add dubai_one.m3u
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Auto-update Dubai One Link"
            git push origin main
          fi
