name: Update Stream Link

on:
  schedule:
    - cron: '0 * * * *' # يعمل كل ساعة
  workflow_dispatch: # يسمح لك بتشغيله يدوياً

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run fetch script
        run: python fetch_link.py

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          # التحقق من وجود الملف قبل عمل add
          if [ -f live_link.txt ]; then
            git add live_link.txt
            # لن يقوم بعمل commit إلا إذا كان هناك تغيير حقيقي في المحتوى
            git commit -m "Update Dubai One Link" || echo "No changes to commit"
            git push
          else
            echo "File live_link.txt not found, skipping..."
            exit 1
          fi
